version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
      - run: make clean
      - run: ./tests/create_user.test.sh
      - run: ./tests/delete_user.test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest